<a href="https://colab.research.google.com/github/davism02/Project-4-Predicting-Hospial-Readmission-for-Diabetes/blob/main/diabetes_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
url ='https://raw.githubusercontent.com/davism02/Project-4-Predicting-Hospial-Readmission-for-Diabetes/main/Resources/diabetic_data.csv'

In [6]:
#Loading libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [8]:
df = pd.read_csv(url)
df.head()

   encounter_id  patient_nbr             race  ... change diabetesMed readmitted
0       2278392      8222157        Caucasian  ...     No          No         NO
1        149190     55629189        Caucasian  ...     Ch         Yes        >30
2         64410     86047875  AfricanAmerican  ...     No         Yes         NO
3        500364     82442376        Caucasian  ...     Ch         Yes         NO
4         16680     42519267        Caucasian  ...     Ch         Yes         NO

[5 rows x 50 columns]

In [9]:
# Include only the interested features

df = df.iloc[:, [2,3,4,5,9,22,41,48, 49]]

df.head()

              race  gender      age  ... insulin  diabetesMed readmitted
0        Caucasian  Female   [0-10)  ...      No           No         NO
1        Caucasian  Female  [10-20)  ...      Up          Yes        >30
2  AfricanAmerican  Female  [20-30)  ...      No          Yes         NO
3        Caucasian    Male  [30-40)  ...      Up          Yes         NO
4        Caucasian    Male  [40-50)  ...  Steady          Yes         NO

[5 rows x 9 columns]

In [10]:
#Checking for missing values in dataset
#In the dataset missing values are represented as '?' sign
for col in df.columns:
    if df[col].dtype == object:
         print(col,df[col][df[col] == '?'].count())

race 2273
gender 0
age 0
weight 98569
max_glu_serum 0
insulin 0
diabetesMed 0
readmitted 0

In [11]:
# Drop rows with invalid values (?)

df = df[(df.race != "?") & (df.gender != "?") & (df.age != "?") & (df.weight != "?")]

df

                   race  gender      age  ... insulin  diabetesMed readmitted
1102          Caucasian    Male  [50-60)  ...  Steady          Yes        >30
1132          Caucasian  Female  [60-70)  ...  Steady          Yes        >30
1136          Caucasian  Female  [40-50)  ...  Steady          Yes         NO
1190          Caucasian  Female  [70-80)  ...  Steady          Yes         NO
1204          Caucasian  Female  [80-90)  ...  Steady          Yes        >30
...                 ...     ...      ...  ...     ...          ...        ...
101456  AfricanAmerican    Male  [60-70)  ...      No           No        >30
101516        Caucasian    Male  [60-70)  ...      No          Yes        >30
101640        Caucasian  Female  [70-80)  ...  Steady          Yes         NO
101667        Caucasian    Male  [70-80)  ...      No          Yes        <30
101723        Caucasian    Male  [60-70)  ...      No          Yes        >30

[3059 rows x 9 columns]

In [12]:
# Convert readmitted column to binary field

df = df.replace({'readmitted': {">30": 0, "NO": 0, "<30": 1}})

df

                   race  gender      age  ... insulin  diabetesMed readmitted
1102          Caucasian    Male  [50-60)  ...  Steady          Yes          0
1132          Caucasian  Female  [60-70)  ...  Steady          Yes          0
1136          Caucasian  Female  [40-50)  ...  Steady          Yes          0
1190          Caucasian  Female  [70-80)  ...  Steady          Yes          0
1204          Caucasian  Female  [80-90)  ...  Steady          Yes          0
...                 ...     ...      ...  ...     ...          ...        ...
101456  AfricanAmerican    Male  [60-70)  ...      No           No          0
101516        Caucasian    Male  [60-70)  ...      No          Yes          0
101640        Caucasian  Female  [70-80)  ...  Steady          Yes          0
101667        Caucasian    Male  [70-80)  ...      No          Yes          1
101723        Caucasian    Male  [60-70)  ...      No          Yes          0

[3059 rows x 9 columns]

In [13]:
#Checking data types of each variable
df.dtypes

race                object
gender              object
age                 object
weight              object
time_in_hospital     int64
max_glu_serum       object
insulin             object
diabetesMed         object
readmitted           int64
dtype: object

In [14]:
# Determine the number of unique values in each column.
df.nunique()

race                 4
gender               2
age                 10
weight               9
time_in_hospital    14
max_glu_serum        1
insulin              4
diabetesMed          2
readmitted           2
dtype: int64

In [15]:
df = df.drop(['max_glu_serum'], axis = 1)

In [17]:
df.to_csv("final_data.csv")

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
df = pd.get_dummies(df,dtype=float)
df.head()

      time_in_hospital  readmitted  ...  diabetesMed_No  diabetesMed_Yes
1102                 2           0  ...             0.0              1.0
1132                 5           0  ...             0.0              1.0
1136                 3           0  ...             0.0              1.0
1190                11           0  ...             0.0              1.0
1204                 9           0  ...             0.0              1.0

[5 rows x 33 columns]

In [ ]:
# Split our preprocessed data into our features and target arrays
y = df['readmitted'].values
y

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state= 42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Compile, Train and Evalutate the Model

In [ ]:
## Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 7)                 231

 dense_5 (Dense)             (None, 14)                112

 dense_6 (Dense)             (None, 21)                315

 dense_7 (Dense)             (None, 1)                 22

=================================================================
Total params: 680
Trainable params: 680
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
61/61 [==============================] - 1s 5ms/step - loss: 0.5682 - accuracy: 0.7732 - val_loss: 0.4129 - val_accuracy: 0.8986
Epoch 2/100
61/61 [==============================] - 0s 3ms/step - loss: 0.4205 - accuracy: 0.8810 - val_loss: 0.3588 - val_accuracy: 0.8986
Epoch 3/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3926 - accuracy: 0.8810 - val_loss: 0.3419 - val_accuracy: 0.8986
Epoch 4/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3821 - accuracy: 0.8810 - val_loss: 0.3366 - val_accuracy: 0.8986
Epoch 5/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3749 - accuracy: 0.8810 - val_loss: 0.3320 - val_accuracy: 0.8986
Epoch 6/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3705 - accuracy: 0.8810 - val_loss: 0.3280 - val_accuracy: 0.8986
Epoch 7/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3667 - accuracy: 0.8810 - val_loss: 0.3290 - val_accuracy: 0.8986
Epoch 8/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3642 - accuracy: 0.8810 - val_loss: 0.3260 - val_accuracy: 0.8986
Epoch 9/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3628 - accuracy: 0.8810 - val_loss: 0.3256 - val_accuracy: 0.8986
Epoch 10/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3605 - accuracy: 0.8810 - val_loss: 0.3255 - val_accuracy: 0.8986
Epoch 11/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3589 - accuracy: 0.8810 - val_loss: 0.3267 - val_accuracy: 0.8986
Epoch 12/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3575 - accuracy: 0.8810 - val_loss: 0.3250 - val_accuracy: 0.8986
Epoch 13/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3567 - accuracy: 0.8810 - val_loss: 0.3256 - val_accuracy: 0.8986
Epoch 14/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3560 - accuracy: 0.8810 - val_loss: 0.3243 - val_accuracy: 0.8986
Epoch 15/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3557 - accuracy: 0.8810 - val_loss: 0.3243 - val_accuracy: 0.8986
Epoch 16/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3547 - accuracy: 0.8810 - val_loss: 0.3250 - val_accuracy: 0.8986
Epoch 17/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3538 - accuracy: 0.8810 - val_loss: 0.3232 - val_accuracy: 0.8986
Epoch 18/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3534 - accuracy: 0.8810 - val_loss: 0.3254 - val_accuracy: 0.8986
Epoch 19/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3527 - accuracy: 0.8810 - val_loss: 0.3258 - val_accuracy: 0.8986
Epoch 20/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3519 - accuracy: 0.8810 - val_loss: 0.3235 - val_accuracy: 0.8986
Epoch 21/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3509 - accuracy: 0.8810 - val_loss: 0.3245 - val_accuracy: 0.8986
Epoch 22/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3501 - accuracy: 0.8810 - val_loss: 0.3234 - val_accuracy: 0.8986
Epoch 23/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3502 - accuracy: 0.8810 - val_loss: 0.3236 - val_accuracy: 0.8986
Epoch 24/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3490 - accuracy: 0.8810 - val_loss: 0.3232 - val_accuracy: 0.8986
Epoch 25/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3494 - accuracy: 0.8810 - val_loss: 0.3233 - val_accuracy: 0.8986
Epoch 26/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3475 - accuracy: 0.8810 - val_loss: 0.3238 - val_accuracy: 0.8986
Epoch 27/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3478 - accuracy: 0.8810 - val_loss: 0.3237 - val_accuracy: 0.8986
Epoch 28/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3467 - accuracy: 0.8810 - val_loss: 0.3236 - val_accuracy: 0.8986
Epoch 29/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3475 - accuracy: 0.8810 - val_loss: 0.3248 - val_accuracy: 0.8986
Epoch 30/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3452 - accuracy: 0.8810 - val_loss: 0.3232 - val_accuracy: 0.8986
Epoch 31/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3455 - accuracy: 0.8810 - val_loss: 0.3247 - val_accuracy: 0.8986
Epoch 32/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3451 - accuracy: 0.8810 - val_loss: 0.3245 - val_accuracy: 0.8986
Epoch 33/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3436 - accuracy: 0.8815 - val_loss: 0.3225 - val_accuracy: 0.8986
Epoch 34/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3433 - accuracy: 0.8815 - val_loss: 0.3246 - val_accuracy: 0.8986
Epoch 35/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3432 - accuracy: 0.8815 - val_loss: 0.3239 - val_accuracy: 0.8986
Epoch 36/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3420 - accuracy: 0.8815 - val_loss: 0.3237 - val_accuracy: 0.8986
Epoch 37/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3423 - accuracy: 0.8815 - val_loss: 0.3244 - val_accuracy: 0.8986
Epoch 38/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3413 - accuracy: 0.8815 - val_loss: 0.3243 - val_accuracy: 0.8986
Epoch 39/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3415 - accuracy: 0.8815 - val_loss: 0.3253 - val_accuracy: 0.8986
Epoch 40/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3413 - accuracy: 0.8815 - val_loss: 0.3243 - val_accuracy: 0.8986
Epoch 41/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3398 - accuracy: 0.8815 - val_loss: 0.3248 - val_accuracy: 0.8986
Epoch 42/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3398 - accuracy: 0.8815 - val_loss: 0.3258 - val_accuracy: 0.8986
Epoch 43/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3400 - accuracy: 0.8815 - val_loss: 0.3247 - val_accuracy: 0.8986
Epoch 44/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3387 - accuracy: 0.8815 - val_loss: 0.3242 - val_accuracy: 0.8986
Epoch 45/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3386 - accuracy: 0.8815 - val_loss: 0.3242 - val_accuracy: 0.8986
Epoch 46/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3373 - accuracy: 0.8815 - val_loss: 0.3242 - val_accuracy: 0.8986
Epoch 47/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3373 - accuracy: 0.8815 - val_loss: 0.3263 - val_accuracy: 0.8986
Epoch 48/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3376 - accuracy: 0.8815 - val_loss: 0.3256 - val_accuracy: 0.8986
Epoch 49/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3364 - accuracy: 0.8815 - val_loss: 0.3263 - val_accuracy: 0.8986
Epoch 50/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3359 - accuracy: 0.8815 - val_loss: 0.3260 - val_accuracy: 0.8986
Epoch 51/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3350 - accuracy: 0.8815 - val_loss: 0.3260 - val_accuracy: 0.8986
Epoch 52/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3346 - accuracy: 0.8815 - val_loss: 0.3261 - val_accuracy: 0.8986
Epoch 53/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3351 - accuracy: 0.8815 - val_loss: 0.3277 - val_accuracy: 0.8986
Epoch 54/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3334 - accuracy: 0.8815 - val_loss: 0.3275 - val_accuracy: 0.8986
Epoch 55/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3325 - accuracy: 0.8815 - val_loss: 0.3291 - val_accuracy: 0.8986
Epoch 56/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3333 - accuracy: 0.8815 - val_loss: 0.3272 - val_accuracy: 0.8986
Epoch 57/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3335 - accuracy: 0.8820 - val_loss: 0.3279 - val_accuracy: 0.8986
Epoch 58/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3314 - accuracy: 0.8815 - val_loss: 0.3293 - val_accuracy: 0.8986
Epoch 59/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3305 - accuracy: 0.8820 - val_loss: 0.3294 - val_accuracy: 0.8986
Epoch 60/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3303 - accuracy: 0.8825 - val_loss: 0.3293 - val_accuracy: 0.8986
Epoch 61/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3308 - accuracy: 0.8815 - val_loss: 0.3306 - val_accuracy: 0.8986
Epoch 62/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3292 - accuracy: 0.8815 - val_loss: 0.3305 - val_accuracy: 0.8986
Epoch 63/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3283 - accuracy: 0.8820 - val_loss: 0.3330 - val_accuracy: 0.8986
Epoch 64/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3299 - accuracy: 0.8825 - val_loss: 0.3320 - val_accuracy: 0.8986
Epoch 65/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3275 - accuracy: 0.8825 - val_loss: 0.3322 - val_accuracy: 0.8986
Epoch 66/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3280 - accuracy: 0.8820 - val_loss: 0.3305 - val_accuracy: 0.8986
Epoch 67/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3269 - accuracy: 0.8825 - val_loss: 0.3305 - val_accuracy: 0.8986
Epoch 68/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3281 - accuracy: 0.8825 - val_loss: 0.3369 - val_accuracy: 0.8986
Epoch 69/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3262 - accuracy: 0.8835 - val_loss: 0.3328 - val_accuracy: 0.8986
Epoch 70/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3261 - accuracy: 0.8835 - val_loss: 0.3345 - val_accuracy: 0.8986
Epoch 71/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3251 - accuracy: 0.8830 - val_loss: 0.3354 - val_accuracy: 0.8986
Epoch 72/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3254 - accuracy: 0.8835 - val_loss: 0.3323 - val_accuracy: 0.8986
Epoch 73/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3257 - accuracy: 0.8835 - val_loss: 0.3336 - val_accuracy: 0.8986
Epoch 74/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3243 - accuracy: 0.8840 - val_loss: 0.3367 - val_accuracy: 0.8986
Epoch 75/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3240 - accuracy: 0.8840 - val_loss: 0.3371 - val_accuracy: 0.8986
Epoch 76/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3239 - accuracy: 0.8830 - val_loss: 0.3380 - val_accuracy: 0.8986
Epoch 77/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3231 - accuracy: 0.8830 - val_loss: 0.3394 - val_accuracy: 0.8986
Epoch 78/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3221 - accuracy: 0.8840 - val_loss: 0.3384 - val_accuracy: 0.8986
Epoch 79/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3250 - accuracy: 0.8835 - val_loss: 0.3368 - val_accuracy: 0.8986
Epoch 80/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3212 - accuracy: 0.8835 - val_loss: 0.3393 - val_accuracy: 0.8986
Epoch 81/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3220 - accuracy: 0.8830 - val_loss: 0.3388 - val_accuracy: 0.8957
Epoch 82/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3200 - accuracy: 0.8846 - val_loss: 0.3389 - val_accuracy: 0.8986
Epoch 83/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3207 - accuracy: 0.8840 - val_loss: 0.3408 - val_accuracy: 0.8986
Epoch 84/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3217 - accuracy: 0.8846 - val_loss: 0.3400 - val_accuracy: 0.8986
Epoch 85/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3203 - accuracy: 0.8840 - val_loss: 0.3444 - val_accuracy: 0.8986
Epoch 86/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3192 - accuracy: 0.8840 - val_loss: 0.3423 - val_accuracy: 0.8957
Epoch 87/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3202 - accuracy: 0.8835 - val_loss: 0.3437 - val_accuracy: 0.8957
Epoch 88/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3193 - accuracy: 0.8846 - val_loss: 0.3427 - val_accuracy: 0.8957
Epoch 89/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3199 - accuracy: 0.8835 - val_loss: 0.3434 - val_accuracy: 0.8957
Epoch 90/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3178 - accuracy: 0.8840 - val_loss: 0.3461 - val_accuracy: 0.8957
Epoch 91/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3183 - accuracy: 0.8846 - val_loss: 0.3456 - val_accuracy: 0.8957
Epoch 92/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3167 - accuracy: 0.8851 - val_loss: 0.3491 - val_accuracy: 0.8928
Epoch 93/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3177 - accuracy: 0.8820 - val_loss: 0.3455 - val_accuracy: 0.8957
Epoch 94/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3165 - accuracy: 0.8851 - val_loss: 0.3503 - val_accuracy: 0.8957
Epoch 95/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3196 - accuracy: 0.8851 - val_loss: 0.3505 - val_accuracy: 0.8957
Epoch 96/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3147 - accuracy: 0.8846 - val_loss: 0.3468 - val_accuracy: 0.8957
Epoch 97/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3157 - accuracy: 0.8856 - val_loss: 0.3521 - val_accuracy: 0.8957
Epoch 98/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3148 - accuracy: 0.8851 - val_loss: 0.3476 - val_accuracy: 0.8957
Epoch 99/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3150 - accuracy: 0.8835 - val_loss: 0.3496 - val_accuracy: 0.8986
Epoch 100/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3140 - accuracy: 0.8851 - val_loss: 0.3497 - val_accuracy: 0.8957

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

24/24 - 0s - loss: 0.3864 - accuracy: 0.8954 - 40ms/epoch - 2ms/step
Loss: 0.3864477276802063, Accuracy: 0.8954248428344727

In [ ]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/Model_1.h5')
files.download('/content/Model_1.h5')